#!/usr/bin/guile \
-e main -s
!#
;; -*- mode: scheme -*-

(define (curr-fname)
  (let [(fname (current-filename))]
    (if fname fname "tester")))

(define (main args)
  (cond [(= 3 (length args))
         (system* (string-append "../" (cadr args))
                  (caddr args))]
        [else
         (display (string-append (curr-fname) " usage: <interpreter> <source.lc>\nexample: " (curr-fname) " scheme-lci 0-identity.lc\n"))]))
